### ISSUE TITLE
Обход ограничения длины строки для входящих параметров

### ISSUE THREAD

**Issue by BlackFan** [themis-project/themis-quals-backend#5]
Ограничение длины строки можно обойти повторением параметров. Длина каждого параметра проверяется отдельно, количество не ограничено, а результат склеивается через запятую.

``` coffee
locality: [new Assert().Length(min: 0, max: 150)]
```

``` http
POST /team/edit-profile HTTP/1.1
...
country=&locality=AAA[..150..]AAA&locality=AAA[..150..]AAA&institution=
```

**Comment by aspyatkin** [comment]
The problem is caused by a validator engine misconfuguration. We need to check explicitly that submitted value has string type. However, the validator engine does not support type checking, so we need implement it with callback. An example of string type checking can be found in [is.js](https://github.com/arasatasaygin/is.js) library
